stages:
  - pull-project
  - build-backend


pull-project:
  stage: pull-project
  script:
    - echo "Pulling project from git"
    - git pull origin main
  only:
    - main


build-backend:
  stage: build-backend
  script:
    - echo "Building backend"
    - docker compose -f docker-compose.yml up --build --remove-orphans -d
  only:
    - main
  dependencies:
    - pull-project