version: "3.9"

services:
  backend:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PIPENV_VENV_IN_PROJECT=1
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_real
      - POSTGRES_PASSWORD=postgres_real
      - POSTGRES_DB=postgres_real
    ports:
      - "5432:5432"
